DEVICE          : cuda                        # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : '/mnt/gpu_storage/cs_courses/jmagana/results/StitchFusion'          # output folder name used for saving the model, logs and inference results
GPUs            : 2
GPU_IDs         : [0, 1]
USE_WANDB       : True
WANDB_NAME      : 'stitchfusion-deliver'             # name for the run

MODEL:
  NAME          : stitchfusion                                         # name of the model you are using
  BACKBONE      : stitchfusion-B3                                      # model variant
  PRETRAINED    : '/mnt/gpu_storage/cs_courses/jmagana/StitchFusion/checkpoints/pretrained/segformers/mit_b3.pth'     # backbone model's weight 
  RESUME        : ''                                                # checkpoint file

DATASET:
  NAME          : DELIVER                                               # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/mnt/gpu_storage/cs_courses/jmagana/StitchFusion/data/DELIVER'                            # dataset root path
  IGNORE_LABEL  : 255
  # MODALS        : ['img']
  # MODALS        : ['img', 'depth']
  # MODALS        : ['img', 'event']
  # MODALS        : ['img', 'lidar']
  # MODALS        : ['img', 'depth', 'event']
  # MODALS        : ['img', 'depth', 'lidar']
  MODALS        : ['img', 'depth', 'event', 'lidar']

TRAIN:
  IMAGE_SIZE    : [512, 512]      # training image size in (h, w) === Fixed in dataloader, following MCubeSNet
  BATCH_SIZE    : 4               # batch size used to train
  EPOCHS        : 50             # number of epochs to train
  EVAL_START    : 1               # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : true           # use AMP in training
  DDP           : true          # use DDP training

LOSS:
  NAME          : OhemCrossEntropy # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.00006         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : '/mnt/gpu_storage/cs_courses/jmagana/results/StitchFusion/CVMac_CVMac-B2_DELIVER_RGBDEL_68.18.pth'                  # Path to your saved model
  IMAGE_SIZE    : [512, 512]                              # evaluation image size in (h, w)                       
  IMAGEROOT     : '/mnt/gpu_storage/cs_courses/jmagana/StitchFusion/data/DELIVER'
  BATCH_SIZE    : 4                                       # batch size
  BATCH_SIZE_VIS: 1
  VIS_SAVE_DIR  : '/mnt/gpu_storage/cs_courses/jmagana/results/StitchFusion/visualization/deliver/rgbde'              # Where to save visualization
  VIS_TSNE_SAVE_DIR : '/mnt/gpu_storage/cs_courses/jmagana/results/StitchFusion/visualization_tsne/deliver/rgbe'              # Where to save visualization
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                
